name = "Bundle Sales"
type = "order_discounts"
api_version = "2022-10"

[build]
command = "cargo wasi build --release"
path = "target/wasm32-wasi/release/ps-bundle-sales.wasm"

[ui.paths]
create = "/ext/discount_code/create"
details = "/ext/discount_code/:id"
