name = "gwp-function"
type = "product_discounts"
api_version = "2023-01"

[build]
command = "cargo wasi build --release"
path = "target/wasm32-wasi/release/gwp-function.wasm"

[ui.paths]
create = "/ext/gift-with-purchase/create"
details = "/ext/gift-with-purchase/:id"
