"""Bundles and Meta Definitions Tables

Revision ID: 7a8babe9123a
Revises: 3ea44c9924cb
Create Date: 2023-04-28 10:17:29.941892

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7a8babe9123a'
down_revision = '3ea44c9924cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bundles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('pid', sa.BigInteger(), nullable=True, comment='Shopify Product ID'),
    sa.Column('vid', sa.BigInteger(), nullable=True, comment='Shopify Variant ID'),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('product_title', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=1024), nullable=True),
    sa.Column('sku', sa.String(length=128), nullable=True),
    sa.Column('barcode', sa.String(length=128), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='0:disable 1:enable'),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bundles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bundles_barcode'), ['barcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_bundles_sku'), ['sku'], unique=False)
        batch_op.create_index('store_shopify_id', ['store_id', 'pid', 'vid'], unique=False)

    op.create_table('meta_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('access', sa.String(length=32), nullable=True),
    sa.Column('md_id', sa.BigInteger(), nullable=True, comment='Meta Definition ID'),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('owner_type', sa.String(length=64), nullable=True),
    sa.Column('namespace', sa.String(length=64), nullable=True),
    sa.Column('key', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('pin', sa.SmallInteger(), nullable=True),
    sa.Column('validations', sa.Text(), nullable=True),
    sa.Column('collection', sa.SmallInteger(), nullable=True),
    sa.Column('store_front', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meta_definitions', schema=None) as batch_op:
        batch_op.create_index('store_key', ['store_id', 'namespace', 'key', 'owner_type'], unique=False)
        batch_op.create_index('store_md_id', ['store_id', 'md_id'], unique=False)

    op.create_table('bundle_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('pid', sa.BigInteger(), nullable=True, comment="Item's Product ID"),
    sa.Column('vid', sa.BigInteger(), nullable=True, comment="Item's Variant ID"),
    sa.Column('title', sa.String(length=255), nullable=True, comment='Variant`s title'),
    sa.Column('image', sa.String(length=1024), nullable=True),
    sa.Column('origin_price', sa.BigInteger(), nullable=True, comment='Origin Price, Cent'),
    sa.Column('price', sa.BigInteger(), nullable=True, comment='Cent'),
    sa.Column('discount', sa.Numeric(precision=5, scale=2), nullable=True, comment='Percentage'),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['bundles.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bundle_items', schema=None) as batch_op:
        batch_op.create_index('store_parent_id', ['store_id', 'parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bundle_items', schema=None) as batch_op:
        batch_op.drop_index('store_parent_id')

    op.drop_table('bundle_items')
    with op.batch_alter_table('meta_definitions', schema=None) as batch_op:
        batch_op.drop_index('store_md_id')
        batch_op.drop_index('store_key')

    op.drop_table('meta_definitions')
    with op.batch_alter_table('bundles', schema=None) as batch_op:
        batch_op.drop_index('store_shopify_id')
        batch_op.drop_index(batch_op.f('ix_bundles_sku'))
        batch_op.drop_index(batch_op.f('ix_bundles_barcode'))

    op.drop_table('bundles')
    # ### end Alembic commands ###
