"""Init basic tables

Revision ID: d2a02178c0dd
Revises: 
Create Date: 2022-02-24 16:56:53.059971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2a02178c0dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stores_key'), 'stores', ['key'], unique=False)
    op.create_table('store_themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('theme_id', sa.BigInteger(), nullable=True),
    sa.Column('theme_name', sa.String(length=128), nullable=True),
    sa.Column('published', sa.SmallInteger(), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_themes_store_id'), 'store_themes', ['store_id'], unique=False)
    op.create_table('webhook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('webhook_id', sa.BigInteger(), nullable=True, comment='Webhook ID'),
    sa.Column('target', sa.String(length=24), nullable=True, comment='Action Target'),
    sa.Column('action', sa.String(length=24), nullable=True, comment='Action'),
    sa.Column('data', sa.Text(length=64000), nullable=True, comment='JSON string'),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webhook')
    op.drop_index(op.f('ix_store_themes_store_id'), table_name='store_themes')
    op.drop_table('store_themes')
    op.drop_index(op.f('ix_stores_key'), table_name='stores')
    op.drop_table('stores')
    # ### end Alembic commands ###
